// Modern ESLint flat config (ESLint v9+).
//
// Migrated from the legacy `.eslintrc.json` + `.eslintignore` + `next lint`
// setup. The full legacy ruleset is preserved verbatim and bridged into flat
// config via `FlatCompat` (the officially supported migration path for
// shareable configs that have not yet shipped native flat presets — here
// `next/core-web-vitals`, `plugin:storybook/recommended`,
// `plugin:@vitest/legacy-recommended`, etc.).
//
// Lint scope mirrors the old behaviour: only first-party source under `src/`
// is linted; submodules, the Next app-router boilerplate, build output and
// tooling files are ignored. Type-aware rules use the modern
// `parserOptions.projectService` (TS-ESLint v8) so out-of-project files no
// longer crash the run the way a hard-coded `project` path would.
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';
import js from '@eslint/js';

const baseDirectory = dirname(fileURLToPath(import.meta.url));

const compat = new FlatCompat({
  baseDirectory,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

export default [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'dist/**',
      'storybook-static/**',
      'coverage/**',
      'docs/**',
      'public/**',
      'app/**',
      'scripts/**',
      '.storybook/**',
      'next-env.d.ts',
      'next.config.js',
      'postcss.config.js',
      'tailwind.config.js',
      'server-wrapper.js',
      'env.sh',
      '*.cjs',
      '*.config.js',
      '*.config.cjs',
      '*.config.mjs',
      // Submodules — each has its own ESLint pipeline and is responsible for
      // linting itself. The parent never loads a submodule's config.
      'src/components/appwrapper/**',
      'src/components/auth/**',
      'src/components/dynamic-form/**',
      'src/lib/next-log/**',
      'src/lib/zod2gql/**',
    ],
  },
  ...compat.config({
    parser: '@typescript-eslint/parser',
    parserOptions: {
      projectService: true,
      tsconfigRootDir: baseDirectory,
    },
    extends: [
      'next/core-web-vitals',
      'prettier',
      'eslint:recommended',
      'plugin:@typescript-eslint/recommended',
      'plugin:eslint-comments/recommended',
      'plugin:import/errors',
      'plugin:import/typescript',
      'plugin:import/warnings',
      'plugin:jsx-a11y/recommended',
      'plugin:optimize-regex/recommended',
      'plugin:prettier/recommended',
      'plugin:promise/recommended',
      'plugin:react-hooks/recommended',
      'plugin:react/recommended',
      'plugin:storybook/recommended',
    ],
    plugins: [
      '@typescript-eslint',
      'eslint-comments',
      'import',
      'jsx-a11y',
      'optimize-regex',
      'prettier',
      'promise',
      'react-hooks',
      'react',
      'security',
      'sonarjs',
      'unused-imports',
    ],
    settings: {
      react: {
        version: 'detect',
      },
    },
    rules: {
      '@typescript-eslint/no-this-alias': 'warn',
      '@typescript-eslint/prefer-for-of': 'warn',
      'import/no-named-as-default-member': 'warn',
      'import/no-named-as-default': 'warn',
      'jsx-a11y/aria-role': 'warn',
      'jsx-a11y/no-redundant-roles': 'warn',
      'jsx-a11y/click-events-have-key-events': 'warn',
      'jsx-a11y/heading-has-content': 'warn',
      'react/no-unknown-property': ['warn', { ignore: ['cmdk-input-wrapper'] }],
      '@typescript-eslint/ban-ts-comment': 'warn',
      'prettier/prettier': [
        'warn',
        {
          printWidth: 125,
          tabWidth: 2,
          useTabs: false,
          semi: true,
          singleQuote: true,
          quoteProps: 'as-needed',
          jsxSingleQuote: true,
          trailingComma: 'all',
          bracketSpacing: true,
          jsxBracketSameLine: false,
          arrowParens: 'always',
          singleAttributePerLine: false,
          endOfLine: 'lf',
        },
      ],
      'react-hooks/exhaustive-deps': ['warn', { additionalHooks: 'useRecoilCallback' }],
      'react/no-set-state': 'warn',
      'react/no-string-refs': 'warn',
      'security/detect-object-injection': 'warn',
      'sonarjs/no-duplicated-branches': 'warn',
      'unused-imports/no-unused-vars': 'off',
      '@typescript-eslint/explicit-function-return-type': 'warn',
      '@typescript-eslint/explicit-module-boundary-types': 'warn',
      '@typescript-eslint/no-empty-function': 'warn',
      '@typescript-eslint/no-inferrable-types': 'warn',
      '@typescript-eslint/no-magic-numbers': 'off',
      '@typescript-eslint/no-namespace': 'warn',
      '@typescript-eslint/no-unused-expressions': 'warn',
      '@typescript-eslint/no-var-requires': 'warn',
      eqeqeq: ['warn', 'always'],
      'eslint-comments/no-unused-disable': 'warn',
      'import/newline-after-import': 'warn',
      'import/no-absolute-path': 'warn',
      'import/no-dynamic-require': 'warn',
      'import/no-extraneous-dependencies': 'warn',
      'import/no-unresolved': 'warn',
      'import/no-useless-path-segments': 'warn',
      'jsx-a11y/accessible-emoji': 'warn',
      'jsx-a11y/alt-text': 'warn',
      'jsx-a11y/anchor-is-valid': 'warn',
      'jsx-a11y/label-has-associated-control': 'warn',
      'no-alert': 'warn',
      'no-console': 'off',
      'no-constant-condition': 'warn',
      'no-debugger': 'warn',
      'no-eq-null': 'warn',
      'no-eval': 'warn',
      'no-implied-eval': 'warn',
      'no-iterator': 'warn',
      'no-lone-blocks': 'warn',
      'no-loop-func': 'warn',
      'no-magic-numbers': 'off',
      'no-multi-str': 'warn',
      'no-new-func': 'warn',
      'no-param-reassign': 'warn',
      'no-return-assign': 'warn',
      'no-script-url': 'warn',
      'no-self-compare': 'warn',
      'no-sequences': 'warn',
      'no-underscore-dangle': 'warn',
      'no-unmodified-loop-condition': 'warn',
      'no-unused-expressions': 'warn',
      'no-unused-vars': 'off',
      'no-useless-concat': 'warn',
      'no-useless-return': 'warn',
      'no-with': 'warn',
      'optimize-regex/optimize-regex': 'warn',
      'promise/always-return': 'warn',
      'promise/catch-or-return': 'warn',
      'promise/no-callback-in-promise': 'warn',
      'promise/no-nesting': 'warn',
      'promise/no-promise-in-callback': 'warn',
      'promise/no-return-in-finally': 'warn',
      'promise/no-return-wrap': 'warn',
      'react-hooks/rules-of-hooks': 'warn',
      'react/react-in-jsx-scope': 'off',
      'react/jsx-boolean-value': 'warn',
      'react/jsx-closing-bracket-location': 'warn',
      'react/jsx-closing-tag-location': 'warn',
      'react/jsx-filename-extension': ['warn', { extensions: ['.jsx', '.tsx'] }],
      'react/jsx-key': 'error',
      'react/jsx-no-bind': 'off',
      'react/jsx-no-comment-textnodes': 'warn',
      'react/jsx-no-duplicate-props': 'warn',
      'react/jsx-no-target-blank': 'warn',
      'react/jsx-no-undef': 'error',
      'react/jsx-no-useless-fragment': 'warn',
      'react/jsx-pascal-case': 'warn',
      'react/jsx-props-no-spreading': 'off',
      'react/jsx-uses-react': 'warn',
      'react/jsx-uses-vars': 'warn',
      'react/no-array-index-key': 'warn',
      'react/no-children-prop': 'warn',
      'react/no-danger-with-children': 'warn',
      'react/no-deprecated': 'warn',
      'react/no-direct-mutation-state': 'warn',
      'react/no-multi-comp': 'off',
      'react/no-unescaped-entities': 'warn',
      'react/no-unstable-nested-components': 'warn',
      'react/no-unused-state': 'warn',
      'react/prefer-stateless-function': 'warn',
      'react/prop-types': 'off',
      'react/self-closing-comp': 'warn',
      'security/detect-buffer-noassert': 'warn',
      'security/detect-child-process': 'warn',
      'security/detect-disable-mustache-escape': 'warn',
      'security/detect-eval-with-expression': 'warn',
      'security/detect-new-buffer': 'warn',
      'security/detect-no-csrf-before-method-override': 'warn',
      'security/detect-non-literal-fs-filename': 'warn',
      'security/detect-non-literal-regexp': 'warn',
      'security/detect-non-literal-require': 'warn',
      'security/detect-possible-timing-attacks': 'warn',
      'security/detect-pseudoRandomBytes': 'warn',
      'security/detect-unsafe-regex': 'warn',
      'sonarjs/cognitive-complexity': 'warn',
      'sonarjs/no-all-duplicated-branches': 'warn',
      'sonarjs/no-duplicate-string': 'warn',
      'sonarjs/no-element-overwrite': 'warn',
      'sonarjs/no-extra-arguments': 'warn',
      'sonarjs/no-identical-conditions': 'warn',
      'sonarjs/no-identical-expressions': 'warn',
      'sonarjs/no-identical-functions': 'warn',
      'sonarjs/no-inverted-boolean-check': 'warn',
      'sonarjs/no-redundant-boolean': 'warn',
      'sonarjs/no-small-switch': 'warn',
      'sonarjs/no-unused-collection': 'warn',
      'sonarjs/no-use-of-empty-return-value': 'warn',
      'sonarjs/no-useless-catch': 'warn',
      'sonarjs/prefer-immediate-return': 'warn',
      'sonarjs/prefer-object-literal': 'warn',
      'sonarjs/prefer-single-boolean-return': 'warn',
      'sonarjs/prefer-while': 'warn',
      yoda: ['warn', 'never'],
      '@typescript-eslint/consistent-type-assertions': 'warn',
      '@typescript-eslint/consistent-type-imports': ['warn', { prefer: 'type-imports' }],
      '@typescript-eslint/consistent-type-exports': ['warn', { fixMixedExportsWithInlineTypeSpecifier: true }],
      '@typescript-eslint/no-import-type-side-effects': 'warn',
      '@typescript-eslint/method-signature-style': ['warn', 'property'],
      '@typescript-eslint/no-useless-empty-export': 'warn',
      '@typescript-eslint/no-empty-interface': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-for-in-array': 'warn',
      '@typescript-eslint/no-non-null-assertion': 'warn',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'warn',
      '@typescript-eslint/no-confusing-non-null-assertion': 'warn',
      '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
      '@typescript-eslint/no-unnecessary-type-arguments': 'warn',
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'warn',
      '@typescript-eslint/no-meaningless-void-operator': 'warn',
      '@typescript-eslint/no-mixed-enums': 'warn',
      '@typescript-eslint/no-duplicate-type-constituents': 'warn',
      '@typescript-eslint/no-redundant-type-constituents': 'warn',
      '@typescript-eslint/no-deprecated': 'warn',
      '@typescript-eslint/no-unsafe-function-type': 'warn',
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/dot-notation': ['warn', { allowIndexSignaturePropertyAccess: true }],
      'dot-notation': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'warn',
      '@typescript-eslint/no-unsafe-member-access': 'warn',
      '@typescript-eslint/no-unsafe-call': 'warn',
      '@typescript-eslint/no-unsafe-return': 'warn',
      '@typescript-eslint/no-unsafe-argument': 'warn',
      '@typescript-eslint/no-floating-promises': 'warn',
      '@typescript-eslint/no-misused-promises': 'warn',
      '@typescript-eslint/await-thenable': 'warn',
      '@typescript-eslint/require-await': 'warn',
      '@typescript-eslint/unbound-method': 'warn',
      '@typescript-eslint/no-base-to-string': 'warn',
      '@typescript-eslint/restrict-template-expressions': 'warn',
      '@typescript-eslint/restrict-plus-operands': 'warn',
      '@typescript-eslint/no-unnecessary-condition': 'warn',
      '@typescript-eslint/strict-boolean-expressions': [
        'warn',
        {
          allowString: true,
          allowNumber: true,
          allowNullableObject: true,
          allowNullableBoolean: false,
          allowNullableString: false,
          allowNullableNumber: false,
          allowAny: false,
        },
      ],
      '@typescript-eslint/prefer-nullish-coalescing': ['warn', { ignorePrimitives: { string: true } }],
      '@typescript-eslint/prefer-optional-chain': 'warn',
      '@typescript-eslint/switch-exhaustiveness-check': 'warn',
      '@typescript-eslint/no-unsafe-enum-comparison': 'warn',
      '@typescript-eslint/prefer-enum-initializers': 'warn',
      '@typescript-eslint/prefer-reduce-type-parameter': 'warn',
      '@typescript-eslint/prefer-return-this-type': 'warn',
      '@typescript-eslint/prefer-includes': 'warn',
      '@typescript-eslint/prefer-string-starts-ends-with': 'warn',
      '@typescript-eslint/prefer-find': 'warn',
      '@typescript-eslint/prefer-readonly': 'warn',
      '@typescript-eslint/require-array-sort-compare': ['warn', { ignoreStringArrays: true }],
      '@typescript-eslint/promise-function-async': 'warn',
      '@typescript-eslint/return-await': ['warn', 'in-try-catch'],
      'no-shadow': 'off',
      '@typescript-eslint/no-shadow': [
        'warn',
        {
          builtinGlobals: true,
          hoist: 'all',
          allow: [
            'event', 'name', 'location', 'origin', 'parent', 'prompt', 'toolbar', 'status', 'length',
            'top', 'close', 'open', 'stop', 'history', 'confirm', 'document', 'innerWidth',
            'innerHeight', 'source', 'selection', 'match',
          ],
        },
      ],
      'no-use-before-define': 'off',
      '@typescript-eslint/no-use-before-define': ['warn', { functions: false, classes: false }],
      'no-new-native-nonconstructor': 'warn',
      'no-duplicate-imports': 'warn',
      'no-self-assign': 'warn',
      '@typescript-eslint/naming-convention': [
        'warn',
        { selector: 'default', format: ['camelCase'], leadingUnderscore: 'allow', trailingUnderscore: 'allow' },
        {
          selector: 'variable',
          format: ['camelCase', 'UPPER_CASE', 'PascalCase'],
          leadingUnderscore: 'allow',
          trailingUnderscore: 'allow',
        },
        { selector: 'parameter', format: ['camelCase', 'PascalCase'], leadingUnderscore: 'allow' },
        { selector: 'function', format: ['camelCase', 'PascalCase'] },
        { selector: 'method', format: ['camelCase', 'PascalCase'], leadingUnderscore: 'allow' },
        { selector: 'typeMethod', format: ['camelCase', 'PascalCase'], leadingUnderscore: 'allow' },
        { selector: 'classicAccessor', format: ['camelCase', 'UPPER_CASE'] },
        { selector: 'memberLike', modifiers: ['private'], format: ['camelCase'], leadingUnderscore: 'allow' },
        {
          selector: 'classProperty',
          modifiers: ['static'],
          format: ['UPPER_CASE', 'camelCase', 'PascalCase'],
          leadingUnderscore: 'allow',
        },
        { selector: 'typeLike', format: ['PascalCase'] },
        { selector: 'enumMember', format: ['UPPER_CASE', 'PascalCase'] },
        { selector: 'objectLiteralProperty', format: null },
        { selector: 'typeProperty', format: null },
        { selector: 'import', format: ['camelCase', 'PascalCase'] },
      ],
      'no-restricted-syntax': [
        'warn',
        {
          selector: "TSAsExpression > TSTypeReference[typeName.name='Record'] > TSTypeParameterInstantiation > TSAnyKeyword",
          message:
            'Avoid `as Record<string, any>`. Type the value precisely; use `Record<string, unknown>` only at framework boundaries.',
        },
        {
          selector: 'TSAsExpression > TSUnknownKeyword',
          message: 'Avoid `as unknown` to bypass type errors. Validate at the boundary and propagate the narrow type.',
        },
        {
          selector: "TSAsExpression[typeAnnotation.type='TSAnyKeyword']",
          message: 'Avoid `as any`. Fix the type at its source.',
        },
        {
          selector: 'TSTypeAnnotation > TSUnknownKeyword',
          message:
            '`unknown` outside `catch` is a smell. Validate at the boundary entry (Zod / type guard) and propagate the narrow type. Catch-clause variables are exempt.',
        },
      ],
      'no-template-curly-in-string': 'warn',
      'no-unreachable-loop': 'warn',
      'no-await-in-loop': 'warn',
      'no-promise-executor-return': 'warn',
      'require-atomic-updates': 'warn',
      'array-callback-return': 'warn',
      'no-constructor-return': 'warn',
      'default-case-last': 'warn',
      'grouped-accessor-pairs': 'warn',
      'no-loss-of-precision': 'warn',
      'no-constant-binary-expression': 'warn',
      'no-lonely-if': 'warn',
      'no-unneeded-ternary': 'warn',
      'prefer-arrow-callback': ['warn', { allowNamedFunctions: true }],
      'prefer-rest-params': 'warn',
      'prefer-const': 'warn',
      'no-var': 'warn',
      complexity: ['warn', 25],
      'max-depth': ['warn', 5],
      curly: ['warn', 'all'],
      'prefer-template': 'warn',
      'no-throw-literal': 'warn',
      'import/no-cycle': ['warn', { maxDepth: 4, ignoreExternal: true }],
      'import/no-self-import': 'warn',
      'import/extensions': ['warn', 'never'],
      'import/first': 'warn',
      'import/no-duplicates': 'warn',
      'import/order': 'warn',
      'jsx-a11y/media-has-caption': 'warn',
      'jsx-a11y/mouse-events-have-key-events': 'warn',
      'jsx-a11y/no-static-element-interactions': 'warn',
      'react/no-danger': 'warn',
      'unused-imports/no-unused-imports': 'warn',
      'import/no-unassigned-import': 'warn',
      'jsx-a11y/no-autofocus': 'warn',
      'react/no-access-state-in-setstate': 'warn',
    },
    overrides: [
      {
        files: ['*.tsx'],
        rules: {
          '@typescript-eslint/explicit-function-return-type': 'off',
          '@typescript-eslint/explicit-module-boundary-types': 'off',
        },
      },
      {
        files: ['**/*.test.ts', '**/*.test.tsx', 'src/__tests__/**/*.ts', 'src/__tests__/**/*.tsx', 'tests/**/*.ts', 'tests/**/*.tsx'],
        plugins: ['@vitest'],
        extends: ['plugin:@vitest/legacy-recommended'],
        rules: {
          '@vitest/no-focused-tests': 'error',
          '@vitest/no-disabled-tests': 'error',
          '@vitest/no-identical-title': 'error',
          '@vitest/consistent-test-it': ['error', { fn: 'it', withinDescribe: 'it' }],
          '@vitest/valid-expect': 'error',
          '@vitest/valid-title': 'error',
          '@vitest/no-conditional-tests': 'warn',
          '@vitest/no-conditional-in-test': 'warn',
          '@vitest/no-conditional-expect': 'error',
        },
      },
    ],
  }),
];
