name: On Push

on:
  push:
    branches-ignore:
      - main
      - dev
permissions:
  contents: write
jobs:
  call-reusable-lint:
    name: Call Reusable Lint Workflow
    uses: JamesonRGrieve/Workflows/.github/workflows/test-ts-lint.yml@main
    with:
      lint_command: 'npm run lint'
      fix_command: 'npm run lint-fix'
  call-reusable-build:
    name: Call Reusable Build and Test Next.js
    uses: JamesonRGrieve/Workflows/.github/workflows/build-next.yml@main # Path to the reusable workflow
    with:
      node-version: '20' # Optional: specify Node.js version, or omit to use default from reusable workflow
    permissions:
      contents: write # Required because the reusable workflow (specifically its lint job) needs it
    secrets: inherit # If the reusable workflow needed secrets, they would be passed like this
